In [3]:
import pandas as pd

df = pd.read_csv("../data/raw/fedfunds.csv")

df.head()

  observation_date  FEDFUNDS
0       1954-07-01      0.80
1       1954-08-01      1.22
2       1954-09-01      1.07
3       1954-10-01      0.85
4       1954-11-01      0.83

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("../data/raw/fedfunds.csv")

In [6]:
df.head()

  observation_date  FEDFUNDS
0       1954-07-01      0.80
1       1954-08-01      1.22
2       1954-09-01      1.07
3       1954-10-01      0.85
4       1954-11-01      0.83

In [7]:
df.head()

  observation_date  FEDFUNDS
0       1954-07-01      0.80
1       1954-08-01      1.22
2       1954-09-01      1.07
3       1954-10-01      0.85
4       1954-11-01      0.83

In [8]:
df.shape

(863, 2)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 863 entries, 0 to 862
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  863 non-null    str
 1   FEDFUNDS          863 non-null    float64
dtypes: float64(1), str(1)
memory usage: 13.6 KB

In [10]:
df.describe()

         FEDFUNDS
count  863.000000
mean     4.598204
std      3.533383
min      0.050000
25%      1.920000
50%      4.270000
75%      6.120000
max     19.100000

In [11]:
df.isnull().sum()

observation_date    0
FEDFUNDS            0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [14]:
print(df.columns)

Index(['observation_date', 'FEDFUNDS'], dtype='str')

In [15]:
df["observation_date"] = pd.to_datetime(df["observation_date"])

In [16]:
df.rename(columns={
    "observation_date": "DATE",
    "DGS10": "RATE"
}, inplace=True)

df["DATE"] = pd.to_datetime(df["DATE"])

In [17]:
print(df.columns)
df.head()

Index(['DATE', 'FEDFUNDS'], dtype='str')

        DATE  FEDFUNDS
0 1954-07-01      0.80
1 1954-08-01      1.22
2 1954-09-01      1.07
3 1954-10-01      0.85
4 1954-11-01      0.83

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 863 entries, 0 to 862
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      863 non-null    datetime64[us]
 1   FEDFUNDS  863 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 13.6 KB

In [19]:
df.set_index("DATE", inplace=True)

In [20]:
df.head()

            FEDFUNDS
DATE
1954-07-01      0.80
1954-08-01      1.22
1954-09-01      1.07
1954-10-01      0.85
1954-11-01      0.83

In [21]:
print(df.columns)

Index(['FEDFUNDS'], dtype='str')

In [22]:
print(df.columns)

Index(['FEDFUNDS'], dtype='str')

In [23]:
df.head(10)

            FEDFUNDS
DATE
1954-07-01      0.80
1954-08-01      1.22
1954-09-01      1.07
1954-10-01      0.85
1954-11-01      0.83
1954-12-01      1.28
1955-01-01      1.39
1955-02-01      1.29
1955-03-01      1.35
1955-04-01      1.43

In [24]:
df.shape

(863, 1)

In [25]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 863 entries, 1954-07-01 to 2026-05-01
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FEDFUNDS  863 non-null    float64
dtypes: float64(1)
memory usage: 13.5 KB

In [26]:
df.head(10)

            FEDFUNDS
DATE
1954-07-01      0.80
1954-08-01      1.22
1954-09-01      1.07
1954-10-01      0.85
1954-11-01      0.83
1954-12-01      1.28
1955-01-01      1.39
1955-02-01      1.29
1955-03-01      1.35
1955-04-01      1.43

In [27]:
df.index

DatetimeIndex(['1954-07-01', '1954-08-01', '1954-09-01', '1954-10-01',
               '1954-11-01', '1954-12-01', '1955-01-01', '1955-02-01',
               '1955-03-01', '1955-04-01',
               ...
               '2025-08-01', '2025-09-01', '2025-10-01', '2025-11-01',
               '2025-12-01', '2026-01-01', '2026-02-01', '2026-03-01',
               '2026-04-01', '2026-05-01'],
              dtype='datetime64[us]', name='DATE', length=863, freq=None)

In [28]:
df = df.reset_index()

print(df.columns)
df.head()

Index(['DATE', 'FEDFUNDS'], dtype='str')

        DATE  FEDFUNDS
0 1954-07-01      0.80
1 1954-08-01      1.22
2 1954-09-01      1.07
3 1954-10-01      0.85
4 1954-11-01      0.83

In [29]:
df = df.reset_index()

df["DATE"] = pd.to_datetime(df["DATE"])

df.head()

   index       DATE  FEDFUNDS
0      0 1954-07-01      0.80
1      1 1954-08-01      1.22
2      2 1954-09-01      1.07
3      3 1954-10-01      0.85
4      4 1954-11-01      0.83

In [30]:
df = df.drop(columns=["index"])

df.head()

        DATE  FEDFUNDS
0 1954-07-01      0.80
1 1954-08-01      1.22
2 1954-09-01      1.07
3 1954-10-01      0.85
4 1954-11-01      0.83

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 863 entries, 0 to 862
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DATE      863 non-null    datetime64[us]
 1   FEDFUNDS  863 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 13.6 KB

In [32]:
df.isnull().sum()

DATE        0
FEDFUNDS    0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.describe()

                             DATE    FEDFUNDS
count                         863  863.000000
mean   1990-06-01 08:45:36.500579    4.598204
min           1954-07-01 00:00:00    0.050000
25%           1972-06-16 00:00:00    1.920000
50%           1990-06-01 00:00:00    4.270000
75%           2008-05-16 12:00:00    6.120000
max           2026-05-01 00:00:00   19.100000
std                           NaN    3.533383