In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/fedfunds.csv")

df["observation_date"] = pd.to_datetime(df["observation_date"])

df.set_index("observation_date", inplace=True)

df.head()

                  FEDFUNDS
observation_date
1954-07-01            0.80
1954-08-01            1.22
1954-09-01            1.07
1954-10-01            0.85
1954-11-01            0.83

In [2]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 863 entries, 1954-07-01 to 2026-05-01
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   FEDFUNDS  863 non-null    float64
dtypes: float64(1)
memory usage: 13.5 KB

In [3]:
df["lag_1"] = df["FEDFUNDS"].shift(1)

In [4]:
df["lag_2"] = df["FEDFUNDS"].shift(2)

In [5]:
df["lag_3"] = df["FEDFUNDS"].shift(3)

In [6]:
df.head(10)

                  FEDFUNDS  lag_1  lag_2  lag_3
observation_date
1954-07-01            0.80    NaN    NaN    NaN
1954-08-01            1.22   0.80    NaN    NaN
1954-09-01            1.07   1.22   0.80    NaN
1954-10-01            0.85   1.07   1.22   0.80
1954-11-01            0.83   0.85   1.07   1.22
1954-12-01            1.28   0.83   0.85   1.07
1955-01-01            1.39   1.28   0.83   0.85
1955-02-01            1.29   1.39   1.28   0.83
1955-03-01            1.35   1.29   1.39   1.28
1955-04-01            1.43   1.35   1.29   1.39

In [7]:
df["rolling_mean_3"] = (
    df["FEDFUNDS"]
    .rolling(window=3)
    .mean()
)

In [8]:
df["rolling_mean_12"] = (
    df["FEDFUNDS"]
    .rolling(window=12)
    .mean()
)

In [9]:
df["rate_change"] = (
    df["FEDFUNDS"]
    .diff()
)

In [10]:
df["pct_change"] = (
    df["FEDFUNDS"]
    .pct_change()
)

In [11]:
df["volatility_12"] = (
    df["FEDFUNDS"]
    .rolling(window=12)
    .std()
)

In [12]:
df["trend"] = np.where(
    df["rate_change"] > 0,
    1,
    0
)

In [13]:
df["year"] = df.index.year

df["month"] = df.index.month

df["quarter"] = df.index.quarter

In [14]:
df.isnull().sum()

FEDFUNDS            0
lag_1               1
lag_2               2
lag_3               3
rolling_mean_3      2
rolling_mean_12    11
rate_change         1
pct_change          1
volatility_12      11
trend               0
year                0
month               0
quarter             0
dtype: int64

In [15]:
df = df.dropna()

In [16]:
df.isnull().sum()

FEDFUNDS           0
lag_1              0
lag_2              0
lag_3              0
rolling_mean_3     0
rolling_mean_12    0
rate_change        0
pct_change         0
volatility_12      0
trend              0
year               0
month              0
quarter            0
dtype: int64

In [17]:
df.to_csv(
    "../data/processed/fedfunds_features.csv"
)

In [18]:
df.columns

Index(['FEDFUNDS', 'lag_1', 'lag_2', 'lag_3', 'rolling_mean_3',
       'rolling_mean_12', 'rate_change', 'pct_change', 'volatility_12',
       'trend', 'year', 'month', 'quarter'],
      dtype='str')

In [19]:
print(df.shape)
print(df.columns)

(852, 13)
Index(['FEDFUNDS', 'lag_1', 'lag_2', 'lag_3', 'rolling_mean_3',
       'rolling_mean_12', 'rate_change', 'pct_change', 'volatility_12',
       'trend', 'year', 'month', 'quarter'],
      dtype='str')